#!/usr/bin/env bash
# script that transfers the file from the client to the server

num=3

if [ "$#" -lt "$num" ]
then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
