#!/usr/bin/env bash

# Bash script to Install nginx web server
apt-get update -y
apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx start

# Script for installing nginx on the intranet server

sudo apt-get update -y
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
