#!/usr/bin/env bash
# The script ensures the the nginx server listens to port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
