#!/usr/bin/env bash
# The script gives a faster way to fix the nginx server
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
